name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker image tags
      id: vars
      run: |
        SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        DATE=$(date +%Y-%m-%d)
        IMAGE=${{ secrets.DOCKER_USERNAME }}/my-image
        VERSION_TAG="${DATE}-${SHORT_SHA}"

        echo "image_tag=${IMAGE}:${VERSION_TAG}" >> $GITHUB_OUTPUT
        echo "latest_tag=${IMAGE}:latest" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ steps.vars.outputs.image_tag }} -t ${{ steps.vars.outputs.latest_tag }} .

    - name: Push Docker image
      run: |
        docker push ${{ steps.vars.outputs.image_tag }}
        docker push ${{ steps.vars.outputs.latest_tag }}