name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up image tag
      id: vars
      run: |
        DATE=$(date +%Y-%m-%d)
        IMAGE_NAME=backend-${DATE}
        echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t toran/${{ steps.vars.outputs.image_name }} .

    - name: Push Docker image
      run: |
        docker push toran/${{ steps.vars.outputs.image_name }}
